### ISSUE TITLE
IPV6 cannot use

### ISSUE THREAD

**Issue by sanphone** [adfansong/easy_socket#1]
when set ipv6 ip, the client will crash!, 
somes like there error, 
`bool SocketWin::connect(int port, const char *ip)
{
    if (sock == -1) {
        setError(0, SocketInvalid);
        EASY_LOG("SocketWin::connect error: invalid socket");
        return false;
    }

```
SockAddr *p = getSockAddr(port, ip);
int ret = ::connect(sock, p->pointer(), p->length());

if (ret == 0) {
    if (del) {
        del->onConnect();
    }
    return true;
} else {
    // unblock
    int error = errno;
    if (ret == -1 && error == WSAEWOULDBLOCK) {
        return true;
    } else {
        setError(error);
        EASY_LOG("SocketLinux::connect error: %s", strerror(error));
        return false;
    }
}
```

}
`
    int ret = ::connect(sock, p->pointer(), p->length());  
ret is -1,  i do not know why?

**Comment by adfansong** [comment]
我刚在windows上测试ipv6没问题，之前也在ios上测过ipv6-only没问题。不知道你的问题在哪儿？你参照main.cpp里代码就可以的。如果是在测试ipv6-only，必须用域名的。

**Comment by sanphone** [comment]
…… 兄弟原来你是同胞啊！ 还以为你是国外的呢！
我是在win10 64bit 测试的，我修改了两个地方，

## 客户端代码

修改的地方：
`
int main(int argc, char _argv[]) {
    *_**const char *ip = "::1";  // 原来是const char *ip = "127.0.0.1";****
    //char ip[] = "::1";
    int port = 9191;

.....
`

## 服务器代码

改的地方SocketBase.cpp当中构造函数：
`SocketBase::SocketBase()
    : **_protocol(6)_**, addr(0), del(0), errorCode(0), 
    set_unblock(true), set_reuseAddr(true), socket_type(SOCK_STREAM)
{

}`

看了下你的代码逻辑，应该就修改这两个地方吧，ivp4我可以测试成功，ipv6的话，server可以正常运行，客户端的话，运行会崩溃，不知是什么意思，望指点！

   非常谢谢！

**Comment by adfansong** [comment]
其实底层Socket里有checkProtocol判断使用哪个协议的，所以在main里面ip = "::1"，下面用listen(port, ip)就行了。。我测试可以连接的。。你再试试

**Comment by sanphone** [comment]
```
Socket::checkProtocol: using ipv6!
start update..
Connection closed.
请按任意键继续. . .
```

根据你的意思，只修改了client中的ip，但是输出内容如上，没有发送任何消息，看了下代码逻辑，不应该这样吧！

**Comment by adfansong** [comment]
下面例子里是listen(port, 0)默认是听的ipv4的，这里也改成listen(port, ip)才行。。
